version: '3'

services:
  # nginx: 
  #   image: nginx:latest
  #   container_name: production_nginx
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #     - 443:443
  db:
    image: "postgres:12-alpine"
    ports:
      - "4000:5432"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  backend:
      build: docker/backend
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./backend:/backend
      ports:
        - "8000:8000"
      depends_on:
        - db
      env_file: ".env"
